### ISSUE TITLE
Crash in 1.18.2

### ISSUE THREAD

**Issue by wsesrdtf** [Pyxrs/Live-Fishing#5]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 22. 3. 30. 오후 2:23
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_3494$class_5123
	at net.minecraft.class_1536.modify$zho000$spawnFish(class_1536.java:685)
	at net.minecraft.class_1536.method_6957(class_1536.java:490)
	at net.minecraft.class_1787.method_7836(class_1787.java:24)
	at net.minecraft.class_1799.method_7913(class_1799.java:262)
	at net.minecraft.class_3225.method_14256(class_3225.java:291)
	at net.minecraft.class_3244.method_12065(class_3244.java:1117)
	at net.minecraft.class_2886.method_12550(class_2886.java:25)
	at net.minecraft.class_2886.method_11054(class_2886.java:7)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3494$class_5123
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 772534184 bytes (736 MiB) / 2080374784 bytes (1984 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600XT 6-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=30.0.14023.7007
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 118891.15
	Virtual memory used (MB): 26293.80
	Swap memory total (MB): 86172.09
	Swap memory used (MB): 968.80
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.48.0+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.7+d7c144a860
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.3+801ec85b60
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.2+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.13+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.3.3+691a79b560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.10+3ac43d9560
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.2+2540745460
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.4+d1027f7d60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.3+40c91ec860
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.17+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.2+d1027f7d60
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.14+40c91ec860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.14+cca23f9360
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+40c91ec860
		fabricloader: Fabric Loader 0.13.3
		fishing: Live Fishing 1.1.0
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.2
	Server Running: true
	Player Count: 1 / 8; [class_3222['wsesrdtf'/139, l='ServerLevel[새로운 세계]', x=-12.13, y=66.00, z=20.04]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by BreadMoirai** [comment]
Here's a deobfuscated version of the stack trace

```java
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 4/1/22, 5:14 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_3494$class_5123
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2)
	at net.minecraft.entity.projectile.FishingBobberEntity.modify$zhc000$spawnFish(FishingBobberEntity:685)
	at net.minecraft.entity.projectile.FishingBobberEntity.use(FishingBobberEntity:490)
	at net.minecraft.item.FishingRodItem.use(FishingRodItem:24)
	at net.minecraft.item.ItemStack.use(ItemStack:262)
	at net.minecraft.server.network.ServerPlayerInteractionManager.interactItem(ServerPlayerInteractionManager:291)
	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractItem(ServerPlayNetworkHandler:1117)
	at net.minecraft.network.packet.c2s.play.PlayerInteractItemC2SPacket.apply(PlayerInteractItemC2SPacket:25)
	at net.minecraft.network.packet.c2s.play.PlayerInteractItemC2SPacket.apply(PlayerInteractItemC2SPacket:7)
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22)
	at net.minecraft.server.ServerTask.run(ServerTask:18)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157)
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:808)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:165)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131)
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:790)
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140)
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:769)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:701)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3494$class_5123
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 22 more
```

**Comment by Pyxrs** [comment]
I don't have enough time to fix this issue at the moment but I'll note the incompatibility in the description... if anyone else would like to fix it, go ahead!

**Comment by Pyxrs** [comment]
No longer relevant
